# Feature Engineering

The objective of this notebook is to transform raw Bitcoin market data into informative features that capture different aspects of market behavior.

These engineered variables will later be used for dimensionality reduction and clustering in order to identify distinct market regimes.

The selected features focus on three fundamental market characteristics:

- Returns (market direction)
- Volatility (market uncertainty)
- Momentum (trend strength)

Together, these variables provide a compact representation of market dynamics.

In [2]:
# Load processed Data
import pandas as pd
import numpy as np
import sys
import os

# Ruta absoluta a la raíz del proyecto
project_root = os.path.abspath("..")
if project_root not in sys.path:
    sys.path.append(project_root)

from config import *

asset_name = ASSETS[0].lower().replace("-", "_")

file_path = f"{RAW_DATA_PATH}/{asset_name}_{INTERVAL}_raw.csv"

df = pd.read_csv(file_path)

df["Date"] = pd.to_datetime(df["Date"])

df.set_index("Date", inplace=True)

df.head()

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2018-01-01,13657.200195,13657.200195,14112.200195,13154.700195,14112.200195,10291200000
2018-01-02,14982.099609,14982.099609,15444.599609,13163.599609,13625.000000,16846600192
2018-01-03,15201.000000,15201.000000,15572.799805,14844.500000,14978.200195,16871900160
2018-01-04,15599.200195,15599.200195,15739.700195,14522.200195,15270.700195,21783199744
2018-01-05,17429.500000,17429.500000,17705.199219,15202.799805,15477.200195,23840899072

-----

## Feature 1: Daily Returns

The first engineered feature is the daily return. Unlike raw prices, returns measure the relative change in value from one trading day to the next.

Returns are widely used in quantitative finance because they provide a standardized measure of market movement that is independent of the asset's absolute price level.

In the context of market regime detection, returns capture the direction and magnitude of daily price movements and serve as a fundamental building block for subsequent features such as volatility and momentum.

This help us estimate how much did the real changed of the asset, relative to its previous value, with the following formula:
$$
r_t = \frac{P_t-P_{t-1}}{P_{t-1}}
$$
Where: 
- $P_t$ = today's price
- $P_{t-1}$ = yesterday's price

In [6]:
# Create Returns Column
df["Returns"] = df["Close"].pct_change() # pct_changes() calculates the daily percentage yields using the formula above

In [7]:
# Verify the new column
df[["Close", "Returns"]].head(10)

                   Close   Returns
Date
2018-01-01  13657.200195       NaN
2018-01-02  14982.099609  0.097011
2018-01-03  15201.000000  0.014611
2018-01-04  15599.200195  0.026196
2018-01-05  17429.500000  0.117333
2018-01-06  17527.000000  0.005594
2018-01-07  16477.599609 -0.059873
2018-01-08  15170.099609 -0.079350
2018-01-09  14595.400391 -0.037884
2018-01-10  14973.299805  0.025892

In [8]:
# Analysis section
df["Returns"].describe()

count    3080.000000
mean        0.001067
std         0.033558
min        -0.371695
25%        -0.013557
50%         0.000629
75%         0.015119
max         0.187465
Name: Returns, dtype: float64